// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
  actor_id, action, table_name, old_values, new_values, ip_address
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, actor_id, action, table_name, old_values, new_values, ip_address, created_at
`

type CreateAuditLogParams struct {
	ActorID   pgtype.UUID `json:"actor_id"`
	Action    string      `json:"action"`
	TableName string      `json:"table_name"`
	OldValues []byte      `json:"old_values"`
	NewValues []byte      `json:"new_values"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TableName,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TableName,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByActorId = `-- name: ListAuditLogsByActorId :many
SELECT id, actor_id, action, table_name, old_values, new_values, ip_address, created_at
FROM audit_logs
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorIdParams struct {
	ActorID pgtype.UUID `json:"actor_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByActorId(ctx context.Context, arg ListAuditLogsByActorIdParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActorId, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TableName,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
