// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
  account_id, transaction_id, credit_debit, amount, balance_after
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, account_id, transaction_id, credit_debit, amount, balance_after, created_at
`

type CreateLedgerEntryParams struct {
	AccountID     int64       `json:"account_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	CreditDebit   string      `json:"credit_debit"`
	Amount        int64       `json:"amount"`
	BalanceAfter  int64       `json:"balance_after"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.AccountID,
		arg.TransactionID,
		arg.CreditDebit,
		arg.Amount,
		arg.BalanceAfter,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.CreditDebit,
		&i.Amount,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccountId = `-- name: ListLedgerEntriesByAccountId :many
SELECT id, account_id, transaction_id, credit_debit, amount, balance_after, created_at
FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountIdParams struct {
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccountId(ctx context.Context, arg ListLedgerEntriesByAccountIdParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccountId, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionID,
			&i.CreditDebit,
			&i.Amount,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
