// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          int64              `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Balance     int64              `json:"balance"`
	Currency    string             `json:"currency"`
	AccountType string             `json:"account_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	TableName string             `json:"table_name"`
	OldValues []byte             `json:"old_values"`
	NewValues []byte             `json:"new_values"`
	IpAddress pgtype.Text        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID            int64              `json:"id"`
	AccountID     int64              `json:"account_id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	CreditDebit   string             `json:"credit_debit"`
	Amount        int64              `json:"amount"`
	BalanceAfter  int64              `json:"balance_after"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                pgtype.UUID        `json:"id"`
	SenderAccountID   pgtype.Int8        `json:"sender_account_id"`
	ReceiverAccountID pgtype.Int8        `json:"receiver_account_id"`
	Amount            int64              `json:"amount"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	TransactionType   string             `json:"transaction_type"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	Phone        string             `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	KycStatus    string             `json:"kyc_status"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
