// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  sender_account_id, receiver_account_id, amount, currency, status, transaction_type, idempotency_key, description
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, sender_account_id, receiver_account_id, amount, currency, status, transaction_type, idempotency_key, description, created_at
`

type CreateTransactionParams struct {
	SenderAccountID   pgtype.Int8 `json:"sender_account_id"`
	ReceiverAccountID pgtype.Int8 `json:"receiver_account_id"`
	Amount            int64       `json:"amount"`
	Currency          string      `json:"currency"`
	Status            string      `json:"status"`
	TransactionType   string      `json:"transaction_type"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
	Description       pgtype.Text `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.SenderAccountID,
		arg.ReceiverAccountID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.TransactionType,
		arg.IdempotencyKey,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderAccountID,
		&i.ReceiverAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.TransactionType,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, sender_account_id, receiver_account_id, amount, currency, status, transaction_type, idempotency_key, description, created_at
FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransactionById(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderAccountID,
		&i.ReceiverAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.TransactionType,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, sender_account_id, receiver_account_id, amount, currency, status, transaction_type, idempotency_key, description, created_at
FROM transactions
WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderAccountID,
		&i.ReceiverAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.TransactionType,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByAccountId = `-- name: ListTransactionsByAccountId :many
SELECT id, sender_account_id, receiver_account_id, amount, currency, status, transaction_type, idempotency_key, description, created_at
FROM transactions
WHERE sender_account_id = $1 OR receiver_account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAccountIdParams struct {
	SenderAccountID pgtype.Int8 `json:"sender_account_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccountId(ctx context.Context, arg ListTransactionsByAccountIdParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountId, arg.SenderAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.SenderAccountID,
			&i.ReceiverAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.TransactionType,
			&i.IdempotencyKey,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
